#  Python Lists — DSA Theory

A **List** in Python is a **dynamic, ordered, mutable sequence** of elements.

##  Characteristics:

* **Indexed:** Items are accessed via zero-based index.
* **Mutable:** You can modify, add, or remove elements.
* **Allows Duplicates:** Lists can have multiple occurrences of the same value.
* **Heterogeneous:** Can store elements of different data types.
* **Dynamic Size:** Lists can grow or shrink as needed during execution.

---

## Common Operations in Lists:

| Operation         | Description                                      |
| :---------------- | :----------------------------------------------- |
| `append()`        | Add an element at the end                        |
| `extend()`        | Add multiple elements from another iterable      |
| `insert()`        | Insert an element at a specified position        |
| `remove()`        | Remove the first occurrence of a specified value |
| `pop()`           | Remove and return an element at a given index    |
| `clear()`         | Remove all elements from the list                |
| `index()`         | Return the first index of a specified value      |
| `count()`         | Count the number of occurrences of a value       |
| `reverse()`       | Reverse the list in-place                        |
| `sort()`          | Sort the list in ascending order (by default)    |
| `copy()`          | Return a shallow copy of the list                |
| `len()`           | Return the number of elements in the list        |
| `sum()`           | Return the sum of all numeric elements           |
| `max()` / `min()` | Return the largest or smallest element           |

---

## Creating a List

In [ ]:
# Creating a list
my_list = [10, 20, 30, 40, 20]
print("List:", my_list)

List: [10, 20, 30, 40, 20]

 # 1. append()

In [2]:
# append() → Adds a single element to the end of the list
numbers = [10, 20, 30]
numbers.append("Kartik")
print("After append:", numbers)  # [10, 20, 30, 40]

After append: [10, 20, 30, 'Kartik']

 # 2. extend()

In [3]:
# extend() → Adds all elements from another iterable (like another list)
numbers = [1, 2, 3]
numbers.extend("kartik")
print("After extend:", numbers)  # [1, 2, 3, 4, 5, 6]

After extend: [1, 2, 3, 'k', 'a', 'r', 't', 'i', 'k']

##  3. insert()

In [ ]:
# insert() → Inserts an element at a specified index
numbers = [1, 3, 4]
numbers.insert(1, 2)  # Insert 2 at index 1
print("After insert:", numbers)  # [1, 2, 3, 4]

# 4. remove ()

In [ ]:
# remove() → Removes the first occurrence of a specified value
numbers = [1, 2, 3, 2]
numbers.remove(2)  # Removes the first 2
print("After remove:", numbers)  # [1, 3, 2]

# 5. pop ()

In [ ]:
# pop() → Removes and returns element at given index (default is last)
numbers = [10, 20, 30]
popped_value = numbers.pop()  # Removes 30
print("Popped value:", popped_value)
print("After pop:", numbers)  # [10, 20]

Popped value: 30
After pop: [10, 20]

# 6. clear ()

In [ ]:
# clear() → Removes all elements from the list
numbers = [10, 20, 30]
numbers.clear()
print("After clear:", numbers)  # []

# 7. index ()

In [ ]:
# index() → Returns the index of the first occurrence of a specified value
numbers = [10, 20, 30, 40]
index_pos = numbers.index(30)
print("Index of 30:", index_pos)  # 2

Index of 30: 2

# 8. count ()

In [ ]:
# count() → Counts the number of times a value occurs in the list
numbers = [1, 2, 3, 2, 4, 2]
count_twos = numbers.count(2)
print("Count of 2:", count_twos)  # 3

# 9. reverse ()

In [ ]:
# reverse() → Reverses the list in-place
numbers = [1, 2, 3, 4]
numbers.reverse()
print("After reverse:", numbers)  # [4, 3, 2, 1]

# 10. sort ()

In [ ]:
# sort() → Sorts the list in ascending order
numbers = [3, 1, 4, 2]
numbers.sort(reverse= True)
print("After sort:", numbers)  # [1, 2, 3, 4]

After sort: [4, 3, 2, 1]

# 11. copy ()

In [ ]:
# copy() → Returns a shallow copy of the list
numbers = [1, 2, 3]
copy_numbers = numbers.copy()
print("Copied list:", copy_numbers)  # [1, 2, 3]

# 12. len ()

In [ ]:
# len() → Returns the number of elements in the list
numbers = [1, 2, 3, 4]
print("Length of list:", len(numbers))  # 4

Length of list: 4

# 13. sum ()

In [ ]:
# sum() → Returns the sum of all numeric elements in the list
numbers = [1, 2, 3, 4]
total = sum(numbers)
print("Sum of list:", total)  # 10

Sum of list: 10

# 14. min () and max ()

In [ ]:
# max() → Returns the largest element in the list
# min() → Returns the smallest element in the list
numbers = [5, 8, 2, 10, 3]
print("Max value:", max(numbers))  # 10
print("Min value:", min(numbers))  # 2

# Problem Statement: List Operations
## Problem:

### A. You are given a list of integers. Write a Python program to perform the following operations sequentially:

1. Append the number 100 to the end of the list.

2. Insert the number 50 at the 3rd position (index 2).

3. Remove the first occurrence of the number 20.

4. Count how many times 10 appears in the list.

5. Reverse the list.

6. Sort the list in ascending order.

7. Find the maximum and minimum values in the list.

8. Calculate the sum of all elements in the list.

1. Append the number 100 to the end of the list

In [ ]:
# Given list
numbers = [10, 20, 30, 40]

# Append 100 to the list
numbers.append(100)

# Print the updated list
print("Updated list after append:", numbers)

2. Insert the number 50 at the 3rd position (index 2).

In [ ]:
# Given list
numbers = [10, 20, 30, 40]

# Insert 50 at index 2 (3rd position)
numbers.insert(2, 50)

# Print the updated list
print("Updated list after insert:", numbers)

3. Remove the first occurrence of the number 20

In [ ]:
# Given list
numbers = [10, 20, 30, 40, 20]

# Remove the first occurrence of 20
numbers.remove(20)

# Print the updated list
print("Updated list after removing 20:", numbers)

4. Count how many times 10 appears in the list.

In [ ]:
# Given list
numbers = [10, 20, 30, 10, 40, 10]

# Count how many times 10 appears
count_of_10 = numbers.count(10)

# Print the count
print("Number of times 10 appears:", count_of_10)

Number of times 10 appears: 3

5. Reverse a List

In [ ]:
# Given list
numbers = [10, 20, 30, 40, 50]

# Reverse the list
numbers.reverse()

# Print the reversed list
print("List after reverse:", numbers)

6. Sort the list in ascending order.

In [ ]:
# Given list
numbers = [50, 20, 40, 10, 30]

# Sort the list in ascending order
numbers.sort()

# Print the sorted list
print("List after sort:", numbers)

7. Find the maximum and minimum values in the list.

In [ ]:
# Given list
numbers = [50, 20, 40, 10, 30]

# Find maximum and minimum values
maximum_value = max(numbers)
minimum_value = min(numbers)

# Print the values
print("Maximum value:", maximum_value)
print("Minimum value:", minimum_value)

8. the sum of all elements in the list.

In [ ]:
# Given list
numbers = [50, 20, 40, 10, 30]

# Calculate the sum of all elements
total_sum = sum(numbers)

# Print the sum
print("Sum of list:", total_sum)